# Generated by Django 5.2.6 on 2025-10-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus_app', '0006_suratizin_kelas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suratizin',
            unique_together={('santri', 'kelas', 'tanggal', 'sesi')},
        ),
    ]
