# Generated by Django 5.2.6 on 2026-02-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus_app', '0003_alter_presensi_unique_together_and_more'),
        ('pengurus_app', '0010_santri_kelas_list'),
    ]

    operations = [
    ]
