# Generated by Django 5.2.6 on 2026-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus_app', '0012_alter_presensi_id_alter_registrationcode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suratizin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='presensi',
            table='presensi',
        ),
        migrations.AlterModelTable(
            name='santri',
            table='santri',
        ),
        migrations.AlterModelTable(
            name='suratizin',
            table='suratizin',
        ),
    ]
