# Generated by Django 5.2.6 on 2026-03-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus_app', '0013_alter_presensi_id_alter_registrationcode_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrationcode',
            table='registrationcode',
        ),
    ]
